### ISSUE TITLE
Allow variations of /tgif

### ISSUE THREAD

**Issue by jaspb** [herschel666/tgif#14]
Allow variations of /tgif.
E.g.
/TGIF
/tgirf
/tgrif

This feature aims at users with autocorrect capitalising tgif to TGIF as well as users speaking the vong X hers language.

Motivated by voxnow.de/rtlnow.de also allowing voxnau.de/rtlnau.de

**Comment by jaspb** [comment]
Further variations include but are not limited to
/tgitf
/tgiff
/tgifff
etc.

Also cover the upper case realisations of these.

**Comment by herschel666** [comment]
`/^(tgir?f|tgrif)$/i` is allowed. no multiple `f`s or more than the leading `t`. I think that's enough.
